/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchluesselRouteImport } from './routes/schluessel'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SaisonkalenderRouteImport } from './routes/saisonkalender'
import { Route as LexiconRouteImport } from './routes/lexicon'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LexiconIndexRouteImport } from './routes/lexicon.index'
import { Route as LexiconIdRouteImport } from './routes/lexicon.$id'

const SchluesselRoute = SchluesselRouteImport.update({
  id: '/schluessel',
  path: '/schluessel',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisonkalenderRoute = SaisonkalenderRouteImport.update({
  id: '/saisonkalender',
  path: '/saisonkalender',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiconRoute = LexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiconIndexRoute = LexiconIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LexiconRoute,
} as any)
const LexiconIdRoute = LexiconIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LexiconRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/lexicon': typeof LexiconRouteWithChildren
  '/saisonkalender': typeof SaisonkalenderRoute
  '/scanner': typeof ScannerRoute
  '/schluessel': typeof SchluesselRoute
  '/lexicon/$id': typeof LexiconIdRoute
  '/lexicon/': typeof LexiconIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/saisonkalender': typeof SaisonkalenderRoute
  '/scanner': typeof ScannerRoute
  '/schluessel': typeof SchluesselRoute
  '/lexicon/$id': typeof LexiconIdRoute
  '/lexicon': typeof LexiconIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/lexicon': typeof LexiconRouteWithChildren
  '/saisonkalender': typeof SaisonkalenderRoute
  '/scanner': typeof ScannerRoute
  '/schluessel': typeof SchluesselRoute
  '/lexicon/$id': typeof LexiconIdRoute
  '/lexicon/': typeof LexiconIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basket'
    | '/lexicon'
    | '/saisonkalender'
    | '/scanner'
    | '/schluessel'
    | '/lexicon/$id'
    | '/lexicon/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basket'
    | '/saisonkalender'
    | '/scanner'
    | '/schluessel'
    | '/lexicon/$id'
    | '/lexicon'
  id:
    | '__root__'
    | '/'
    | '/basket'
    | '/lexicon'
    | '/saisonkalender'
    | '/scanner'
    | '/schluessel'
    | '/lexicon/$id'
    | '/lexicon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasketRoute: typeof BasketRoute
  LexiconRoute: typeof LexiconRouteWithChildren
  SaisonkalenderRoute: typeof SaisonkalenderRoute
  ScannerRoute: typeof ScannerRoute
  SchluesselRoute: typeof SchluesselRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schluessel': {
      id: '/schluessel'
      path: '/schluessel'
      fullPath: '/schluessel'
      preLoaderRoute: typeof SchluesselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisonkalender': {
      id: '/saisonkalender'
      path: '/saisonkalender'
      fullPath: '/saisonkalender'
      preLoaderRoute: typeof SaisonkalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexicon': {
      id: '/lexicon'
      path: '/lexicon'
      fullPath: '/lexicon'
      preLoaderRoute: typeof LexiconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexicon/': {
      id: '/lexicon/'
      path: '/'
      fullPath: '/lexicon/'
      preLoaderRoute: typeof LexiconIndexRouteImport
      parentRoute: typeof LexiconRoute
    }
    '/lexicon/$id': {
      id: '/lexicon/$id'
      path: '/$id'
      fullPath: '/lexicon/$id'
      preLoaderRoute: typeof LexiconIdRouteImport
      parentRoute: typeof LexiconRoute
    }
  }
}

interface LexiconRouteChildren {
  LexiconIdRoute: typeof LexiconIdRoute
  LexiconIndexRoute: typeof LexiconIndexRoute
}

const LexiconRouteChildren: LexiconRouteChildren = {
  LexiconIdRoute: LexiconIdRoute,
  LexiconIndexRoute: LexiconIndexRoute,
}

const LexiconRouteWithChildren =
  LexiconRoute._addFileChildren(LexiconRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasketRoute: BasketRoute,
  LexiconRoute: LexiconRouteWithChildren,
  SaisonkalenderRoute: SaisonkalenderRoute,
  ScannerRoute: ScannerRoute,
  SchluesselRoute: SchluesselRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
